// Auth action types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAILURE = 'GOOGLE_LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

// Bookings action types
export const GET_BOOKINGS_REQUEST = 'GET_BOOKINGS_REQUEST';
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_FAILURE = 'GET_BOOKINGS_FAILURE';

export const GET_BOOKING_REQUEST = 'GET_BOOKING_REQUEST';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAILURE = 'GET_BOOKING_FAILURE';

export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE';

export const CANCEL_BOOKING_REQUEST = 'CANCEL_BOOKING_REQUEST';
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_FAILURE = 'CANCEL_BOOKING_FAILURE';

// Photographers action types
export const GET_PHOTOGRAPHERS_REQUEST = 'GET_PHOTOGRAPHERS_REQUEST';
export const GET_PHOTOGRAPHERS_SUCCESS = 'GET_PHOTOGRAPHERS_SUCCESS';
export const GET_PHOTOGRAPHERS_FAILURE = 'GET_PHOTOGRAPHERS_FAILURE';

export const GET_PHOTOGRAPHER_REQUEST = 'GET_PHOTOGRAPHER_REQUEST';
export const GET_PHOTOGRAPHER_SUCCESS = 'GET_PHOTOGRAPHER_SUCCESS';
export const GET_PHOTOGRAPHER_FAILURE = 'GET_PHOTOGRAPHER_FAILURE';

// Mercure (real-time) action types
export const MERCURE_CONNECT_REQUEST = 'MERCURE_CONNECT_REQUEST';
export const MERCURE_CONNECTED = 'MERCURE_CONNECTED';
export const MERCURE_DISCONNECTED = 'MERCURE_DISCONNECTED';
export const MERCURE_DISCONNECT_REQUEST = 'MERCURE_DISCONNECT_REQUEST';
export const MERCURE_ERROR = 'MERCURE_ERROR';

// Mercure incoming data events
export const MERCURE_BOOKING_CREATED = 'MERCURE_BOOKING_CREATED';
export const MERCURE_BOOKING_UPDATED = 'MERCURE_BOOKING_UPDATED';
export const MERCURE_BOOKING_CANCELLED = 'MERCURE_BOOKING_CANCELLED';
export const MERCURE_PHOTOGRAPHER_UPDATED = 'MERCURE_PHOTOGRAPHER_UPDATED';
export const MERCURE_PROFILE_UPDATED = 'MERCURE_PROFILE_UPDATED';

// Notifications
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ';
export const CLEAR_ALL_NOTIFICATIONS = 'CLEAR_ALL_NOTIFICATIONS';
export const SET_LAST_KNOWN_STATUS = 'SET_LAST_KNOWN_STATUS';